### ISSUE TITLE
Error:  install skt with the beaker extras

### ISSUE THREAD

**Issue by danghai** [RH-FMK/skt#103]
I got error when I try to install skt with the beaker extras:
```
$ pip install git+https://github.com/RH-FMK/skt[beaker]
```
The error log: 
```
Collecting git+https://github.com/RH-FMK/skt[beaker]
  Cloning https://github.com/RH-FMK/skt[beaker] to /tmp/pip-req-build-d_wNVQ
fatal: unable to access 'https://github.com/RH-FMK/skt[beaker]/': The requested URL returned error: 400
Command "git clone -q https://github.com/RH-FMK/skt[beaker] /tmp/pip-req-build-d_wNVQ" failed with error code 128 in None
```
Could you help me figure out it? Thanks

**Comment by veruu** [comment]
@major since you wrote the installation guide, can you take a look at this? I can verify I get the same error with pip 10.0.1. For this to work for me, we are missing the `.git` suffix to the repo (`pip install git+https://github.com/RH-FMK/skt.git[beaker]`) but maybe you wrote it for a version where it worked differently?

**Comment by major** [comment]
Sure. Let me see what is happening in pip >= 10.
