### ISSUE TITLE
Consider making skt.ktree.dumpinfo accept absolute file paths as well

### ISSUE THREAD

**Issue by spbnick** [RH-FMK/skt#57]

**Comment by veruu** [comment]
This shouldn't be hard to fix using `os.path.abspath()` which works with both relative and absolute paths (+ relevant docs). I might take a look if I have time later.

**Comment by danghai** [comment]
@veruu Could you elaborate it by an example? What is an example of an absolute file path, and what is expect output path?

**Comment by danghai** [comment]
Ah I knew a little bit about the `path` before. I just want to confirm that I I understand the issue correctly. Sorry make you confused about my simple question. In particular, the function already handled the `relative path` input. It means when input is `buildinfo.csv` by default--> return path would be `skt-workdir/buildinfo.csv` (or `relative-path/skt-work/buildinfo.csv` with no default input).
when input is an absolute path `/.../buildinfo.csv`, the output would be `/.../skt-workdir/buidinfo.csv` . Is it correct?

**Comment by danghai** [comment]
@veruu  I think using `os.path.abspath()` can make skt.ktree.dumpinfo accept absolute file paths: https://github.com/danghai/skt/commit/cdff467985ac1e27e2f920d77b91f47e4b2c9f41

**Comment by veruu** [comment]
@danghai in theory, yes (see my first comment on the issue). However, we need to verify there isn't another assumption about it later in the code which would expect something about the path and break things. We didn't have time to check it yet, do you think you can take a proper look?

Also, since @major added the `full_path` function, can you use that instead?

**Comment by danghai** [comment]
@veruu sure

**Comment by veruu** [comment]
The functionality using this was removed
